### ISSUE TITLE
Latham 1's missing parallax

### ISSUE THREAD

**Issue by GurrenLagannTSS** [ucc23/ucc#37]
A distance is given for Latham 1 in the Fundamental Parameters section, but no parallax is included. Maybe we could have the parallaxes to be derived from their distances if given in the Fundamental Parameters section.

**Comment by Gabriel-p** [comment]
All OCs have parallax values assigned, estimated from the selected members. The problem with this OC is that it's a complicated object and its members where poorly identified, hence the non-physical (negative) parallax value.

The idea is to separate the values obtained from the photometry+parallax+PMs from the fundamental parameters obtained through some form of isochrone fitting. That is why those blocks of data are separated.
