### ISSUE TITLE
Pages don't show tags

### ISSUE THREAD

**Issue by Gabriel-p** [ucc23/ucc#9]
Testing with https://github.com/ucc23/ucc/blob/main/_pages/alessi1.md, althuogh there are added tags they don't show in the live page https://ucc.ar/alessi1/ and also the Tags page is empty  https://ucc.ar/tags/

**Comment by manaspz** [comment]
What you wish to achieve: Have all the posts inside _clusters linked in a single page (preferably automatically)

Is that correct ?

**Comment by manaspz** [comment]
I think its not wise to digress from the objective.
What do you want each page to do and how is the website supposed to behave (a small system design)?

Maybe I can then propose a better solution !

**Comment by Gabriel-p** [comment]
The website is supposed to stay as it is as much as possible. I would just like to add some tags to _some_ of the entries currently in the  `_clusters` folder, and have those tags show in the Tags page. That's it!

**Comment by Gabriel-p** [comment]
> As far as I am aware the tags section is not meant for the objective you intend to achieve. The tags are meant to be a reference for the search function. If you search something the script searches for the tags of those posts and displays the result.

Mmm now that you mention this I appear to have removed the `search.json` file that was originally located in the top folder. Maybe that's causing the Tags page to be empty?

**Comment by Gabriel-p** [comment]
I realize after all this that this is an unnecessarily complicated way to do what I need. Thank you for your help!

**Comment by manaspz** [comment]
> The website is supposed to stay as it is as much as possible. I would just like to add some tags to _some_ of the entries currently in the `_clusters` folder, and have those tags show in the Tags page. That's it!

This will be a tricky thing to pull of, because the posts will have to show up if they have to be auto generated !
If you decide to make them as pages, you would require defining the script to search specifically in page tags.

I hope this helps and you can actually implement whatever you intend to.

**Comment by Gabriel-p** [comment]
Thank you very much for your help @manaspz!
